/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function isReactCompilerRequired(code: Buffer, signal?: AbortSignal | undefined | null): Promise<boolean>

export declare function isReactCompilerRequiredSync(code: Buffer): boolean
