[package]
edition.workspace = true
license.workspace = true
name              = "swc-releaser"
publish           = false
repository        = { workspace = true }
version           = "0.1.0"

[dependencies]
anyhow         = { workspace = true }
cargo_metadata = { workspace = true }
changesets     = { workspace = true }
clap           = { version = "4.6.0", features = ["derive"] }
indexmap       = { workspace = true }
petgraph       = { workspace = true }
